set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on' 

set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set-option -g mouse on
set -g @scroll-down-exit-copy-mode "off"

# set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin '2KAbhishek/tmux2k'
set -g @tmux2k-refresh-rate 5

set -g @tmux2k-left-plugins "session uptime"
set -g @tmux2k-right-plugins "cpu ram" # gpu

set -g @tmux2k-window-list-left-sep ''
set -g @tmux2k-window-list-right-sep ''

set -g @tmux2k-theme 'onedark'
set -g @tmux2k-session-colors "light_red text"
set -g @tmux2k-uptime-colors "gray text"
set -g @tmux2k-bg-main 'default'  # transparent bar bg

# Binds
unbind C-b
set -g prefix C-s
bind C-s send-prefix

bind r source ~/.config/tmux/tmux.conf \; display "Reloaded"

#
#
#
#
#
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
